name: testing

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.8
      - name: Caching
        uses: actions/cache@v2
        with:
          path: $/{/{ env.pythonLocation /}/}
          key: $/{/{ env.pythonLocation /}/}-$/{/{ hashFiles('setup.py') /}/}-$/{/{ hashFiles('requirements.txt') /}/}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run django integratin test
        run: |
          python manage.py runserver 127.0.0.1:8000
          sleep 20
          python manage.py test
          kill -9 `lsof -i:8000 -t`


